"""
Data models for the Product Review Analysis Workflow.

These models define the core data structures used throughout the multi-agent workflow system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# Re-export orchestrator models for convenience
__all__ = [
    "Insight",
    "ThoughtStep",
    "NextAction",
    "SynthesisThought",
    "QueryClassification",
    "ExecutionContext",
    "VisualizationResult",
    "StepResult",
    "RetryConfig",
]


class Insight(BaseModel):
    """
    Standardized insight generated by analysis agents.
    
    All specialized agents (Sentiment, Topic Modeling, Anomaly Detection, Summary)
    return insights in this format for consistent synthesis.
    """
    
    source_agent: str = Field(..., description="Name of the agent that generated this insight")
    insight_text: str = Field(..., description="Human-readable description of the insight")
    severity_score: float = Field(..., ge=0.0, le=1.0, description="Severity/importance score (0.0 to 1.0)")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in this insight (0.0 to 1.0)")
    supporting_reviews: List[str] = Field(default_factory=list, description="Review IDs that support this insight")
    
    # Visualization hints
    visualization_hint: Optional[str] = Field(None, description="Suggested visualization type (bar_chart, line_chart, pie_chart, etc.)")
    visualization_data: Optional[Dict[str, Any]] = Field(None, description="Data structure for visualization generation")
    
    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Agent-specific metadata")
    
    class Config:
        json_schema_extra = {
            "example": {
                "source_agent": "sentiment",
                "insight_text": "Performance aspect has 78% negative sentiment across 35 reviews",
                "severity_score": 0.78,
                "confidence_score": 0.92,
                "supporting_reviews": ["rev_123", "rev_456"],
                "visualization_hint": "bar_chart",
                "visualization_data": {
                    "x": ["Performance", "Features", "Support"],
                    "y": [0.78, 0.45, 0.62],
                    "chart_type": "bar",
                    "title": "Negative Sentiment by Aspect"
                },
                "metadata": {"aspect": "performance", "total_reviews": 35}
            }
        }


class ThoughtStep(BaseModel):
    """
    Reasoning step before taking action (part of ReAct pattern).
    
    Captures the agent's internal reasoning process before executing an action.
    """
    
    step_id: str = Field(..., description="Unique identifier for this thought step")
    rationale: str = Field(..., description="Detailed explanation of why this action is needed")
    alternatives_considered: List[str] = Field(default_factory=list, description="Other options that were rejected")
    expected_outcome: str = Field(..., description="What we expect to learn from this action")
    
    class Config:
        json_schema_extra = {
            "example": {
                "step_id": "thought_1",
                "rationale": "The user wants to identify product gaps. I need to first understand what data is available.",
                "alternatives_considered": ["Start with topic modeling", "Start with sentiment analysis"],
                "expected_outcome": "I will learn which datasets exist, their size, and what fields are available for analysis."
            }
        }


class NextAction(BaseModel):
    """
    Single next action to take in the workflow (part of ReAct pattern).
    
    Represents one step in the iterative planning process.
    """
    
    action_id: str = Field(..., description="Unique identifier for this action")
    agent_type: str = Field(..., description="Type of agent to execute (data_retrieval, sentiment, topic, etc.)")
    action: str = Field(..., description="Specific action to perform")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the action")
    thought: ThoughtStep = Field(..., description="Reasoning behind this action")
    can_run_parallel_with: List[str] = Field(default_factory=list, description="Other action_ids that can run concurrently")
    is_final: bool = Field(default=False, description="True if this is the last action before synthesis")
    
    class Config:
        json_schema_extra = {
            "example": {
                "action_id": "action_1",
                "agent_type": "data_retrieval",
                "action": "get_user_datasets_with_eda",
                "parameters": {"user_id": "user_123"},
                "thought": {
                    "step_id": "thought_1",
                    "rationale": "Need to understand available data",
                    "alternatives_considered": [],
                    "expected_outcome": "Learn about datasets"
                },
                "can_run_parallel_with": [],
                "is_final": False
            }
        }


class SynthesisThought(BaseModel):
    """
    Synthesis agent's plan before generating response.
    
    Captures the synthesis strategy and organization decisions.
    """
    
    outline: List[str] = Field(..., description="Section headings in order")
    key_insights: List[str] = Field(..., description="Insight IDs to highlight")
    visualization_placements: Dict[str, int] = Field(default_factory=dict, description="Insight ID -> section index mapping")
    narrative_strategy: str = Field(..., description="Strategy for organizing content (problem-solution, chronological, severity-based)")
    reasoning: str = Field(..., description="Why this structure was chosen")
    
    class Config:
        json_schema_extra = {
            "example": {
                "outline": ["Executive Summary", "Top 3 Product Gaps", "Recommendations"],
                "key_insights": ["insight_topic_1", "insight_sentiment_2"],
                "visualization_placements": {"insight_topic_1": 1},
                "narrative_strategy": "severity-based",
                "reasoning": "Organizing by severity because user asked for 'main' gaps"
            }
        }


class QueryClassification(BaseModel):
    """
    Classification result from Coordinator Agent.
    
    Determines how the query should be routed and processed.
    """
    
    complexity: str = Field(..., description="Query complexity (simple, medium, complex)")
    requires_data_retrieval: bool = Field(..., description="Whether data retrieval is needed")
    suggested_route: str = Field(..., description="Suggested routing (direct_response, planner)")
    reasoning: str = Field(..., description="Explanation of the classification")
    
    class Config:
        json_schema_extra = {
            "example": {
                "complexity": "complex",
                "requires_data_retrieval": True,
                "suggested_route": "planner",
                "reasoning": "Query requires multi-step analysis of review data"
            }
        }


@dataclass
class ExecutionContext:
    """
    Shared context across workflow execution and conversation turns.
    
    Maintains state throughout the workflow execution and across multiple
    conversation turns for follow-up queries.
    """
    
    # Core identifiers
    user_id: str
    session_id: str
    message_id: str
    query: str
    
    # User data
    user_datasets: List[Dict[str, Any]] = field(default_factory=list)
    
    # Current execution state
    current_step: Optional[str] = None
    execution_plan: Optional[Dict[str, Any]] = None
    agent_outputs: Dict[str, Any] = field(default_factory=dict)
    insights: List[Insight] = field(default_factory=list)
    completed_steps: set = field(default_factory=set)
    failed_steps: Dict[str, str] = field(default_factory=dict)
    
    # Conversational context (persisted across turns)
    conversation_history: List[Dict[str, Any]] = field(default_factory=list)
    cached_results: Dict[str, Any] = field(default_factory=dict)
    last_visualization_data: Optional[Dict[str, Any]] = None
    
    # Caching and optimization
    cache: Dict[str, Any] = field(default_factory=dict)
    
    # Thread safety for parallel execution
    lock: Any = None  # asyncio.Lock instance
    
    # Timestamps
    started_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


class VisualizationResult(BaseModel):
    """
    Result from Visualization Agent.
    
    Contains information about generated visualizations.
    """
    
    filepath: str = Field(..., description="Path to the generated visualization file")
    chart_type: str = Field(..., description="Type of chart (bar, line, pie, scatter)")
    title: str = Field(..., description="Chart title")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional visualization metadata")
    
    class Config:
        json_schema_extra = {
            "example": {
                "filepath": "/static/visualizations/abc123.png",
                "chart_type": "bar",
                "title": "Negative Sentiment by Aspect",
                "metadata": {"width": 800, "height": 600}
            }
        }


class StepResult(BaseModel):
    """
    Result from executing a single workflow step.
    
    Used by the orchestrator to track step execution outcomes.
    """
    
    success: bool = Field(..., description="Whether the step executed successfully")
    output: Optional[Any] = Field(None, description="Output from the step")
    error: Optional[str] = Field(None, description="Error message if step failed")
    duration_ms: Optional[int] = Field(None, description="Execution duration in milliseconds")
    
    class Config:
        json_schema_extra = {
            "example": {
                "success": True,
                "output": {"reviews": []},
                "error": None,
                "duration_ms": 150
            }
        }


class RetryConfig(BaseModel):
    """
    Configuration for retry logic in the orchestrator.
    
    Defines retry behavior for failed agent executions.
    """
    
    max_retries: int = Field(default=3, description="Maximum number of retry attempts")
    backoff_factor: float = Field(default=2.0, description="Exponential backoff multiplier")
    initial_delay_seconds: float = Field(default=1.0, description="Initial delay before first retry")
    max_delay_seconds: float = Field(default=30.0, description="Maximum delay between retries")
    
    class Config:
        json_schema_extra = {
            "example": {
                "max_retries": 3,
                "backoff_factor": 2.0,
                "initial_delay_seconds": 1.0,
                "max_delay_seconds": 30.0
            }
        }
